### ISSUE TITLE
spec tests fail when run on non-Debian OSes

### ISSUE THREAD

**Issue by op-ct** [voxpupuli/puppet-confluence#135]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: any
- Ruby: any
- Distribution: any
- Module version: any

## How to reproduce

On a non-Debain OS (I used Fedora), run
```sh
SPEC_OPTS=--fail-fast PUPPET_VERSION="~> 4.0" bundle exec rake spec_standalone
```

## What are you seeing

Test failures not seen on Travis:

```
     RuntimeError:
       Could not find the daemon directory (tested [/etc/sv,/var/lib/service])
```

## What behaviour did you expect instead

The spec tests should run consistently regardless of the OS

## Output log

```
SPEC_OPTS=--fail-fast PUPPET_VERSION="~> 4.0" bundle exec rake spec_standalone

Could not find semantic_puppet gem, falling back to internal functionality. Version checks may be less robust.
/home/op-ct/.rvm/rubies/ruby-2.1.9/bin/ruby -I/home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-core-3.6.0/lib:/home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-support-3.6.0/lib /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color
[32m[Coveralls] Set up the SimpleCov formatter.[0m
[32m[Coveralls] Using SimpleCov's default settings.[0m

confluence
  confluence::config
    default params
      should compile into a catalogue without dependency cycles (FAILED - 1)

Failures:

  1) confluence confluence::config default params should compile into a catalogue without dependency cycles
     Failure/Error: it { is_expected.to compile.with_all_deps }

     RuntimeError:
       Could not find the daemon directory (tested [/etc/sv,/var/lib/service])
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/provider/service/runit.rb:50:in `defpath'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type/service.rb:180:in `block (3 levels) in <module:Puppet>'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type.rb:834:in `set_default'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:67:in `call'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-puppet-2.6.8/lib/rspec-puppet/monkey_patches.rb:67:in `block in <class:Type>'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type.rb:2505:in `block in set_parameters'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type.rb:2504:in `each'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type.rb:2504:in `set_parameters'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/type.rb:2401:in `initialize'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource.rb:524:in `new'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource.rb:524:in `to_ral'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource/catalog.rb:633:in `block in to_catalog'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource/catalog.rb:625:in `each'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource/catalog.rb:625:in `to_catalog'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/puppet-4.10.7/lib/puppet/resource/catalog.rb:506:in `to_ral'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-puppet-2.6.8/lib/rspec-puppet/matchers/compile.rb:142:in `cycles_found?'
     # /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-puppet-2.6.8/lib/rspec-puppet/matchers/compile.rb:25:in `matches?'
     # ./spec/classes/confluence_config_spec.rb:20:in `block (4 levels) in <top (required)>'

Finished in 1.64 seconds (files took 1.43 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/classes/confluence_config_spec.rb:20 # confluence confluence::config default params should compile into a catalogue without dependency cycles


Total resources:   20
Touched resources: 0
Resource coverage:  0.00%
Untouched resources:

  Anchor[confluence::end]
  Anchor[confluence::start]
  Archive[/tmp/atlassian-confluence-5.5.6.tar.gz]
  Augeas[/opt/confluence/atlassian-confluence-5.5.6/conf/server.xml]
  Class[Confluence::Config]
  Class[Confluence::Facts]
  Class[Confluence::Install]
  Class[Confluence::Params]
  Class[Confluence::Service]
  Exec[chown_/opt/confluence/atlassian-confluence-5.5.6]
  File[/etc/facter/facts.d/confluence_facts.sh]
  File[/etc/init.d/confluence]
  File[/home/confluence]
  File[/opt/confluence/atlassian-confluence-5.5.6/bin/setenv.sh]
  File[/opt/confluence/atlassian-confluence-5.5.6/confluence/WEB-INF/classes/confluence-init.properties]
  File[/opt/confluence/atlassian-confluence-5.5.6]
  File[/opt/confluence]
  Group[confluence]
  Service[confluence]
  User[confluence]
[33m[Coveralls] Outside the CI environment, not sending data.[0m
/home/op-ct/.rvm/rubies/ruby-2.1.9/bin/ruby -I/home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-core-3.6.0/lib:/home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-support-3.6.0/lib /home/op-ct/.rvm/gems/ruby-2.1.9/gems/rspec-core-3.6.0/exe/rspec --pattern spec/\{aliases,classes,defines,unit,functions,hosts,integration,type_aliases,types\}/\*\*/\*_spec.rb --color failed
```

## Any additional information you'd like to impart

* The default facts in `spec/spec_helper.rb` refer to Debian, but the facts in each spec test sparsely model Redhat.  
* It would be great if the spec tests covered factsets sampled from each OS supported in `metadata.json`

**Comment by baurmatt** [comment]
Aus #136 got merged, I'm closing this issue.
